-- 0012_messages_trace_fields.sql
--
-- Adds per-message observability fields used by Phase B (Langfuse).
-- Every outbound row generated by the agent loop carries:
--   - langfuse_trace_id — link to the trace in Langfuse Cloud
--   - prompt_version_id — exact prompt row used to generate the reply
--                         (so we can replay & A/B test deterministically)
--   - tokens_input / tokens_output — Claude usage breakdown
--   - cost_usd — computed cost for this turn (Sonnet 4.6 rates)
--
-- All new columns are nullable. Outbound rows from before this migration,
-- and inbound rows, leave them NULL.
--
-- The existing `tokens_used` + `ai_processing_time_ms` columns stay as
-- they are; we now also capture the input/output split which is what
-- Langfuse and cost analysis need.

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS langfuse_trace_id text,
  ADD COLUMN IF NOT EXISTS prompt_version_id uuid REFERENCES public.prompts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS tokens_input integer,
  ADD COLUMN IF NOT EXISTS tokens_output integer,
  ADD COLUMN IF NOT EXISTS cost_usd numeric(10, 6);

COMMENT ON COLUMN public.messages.langfuse_trace_id IS
  'Langfuse trace id for the agent turn that produced this message. Use '
  'with LANGFUSE_BASE_URL/trace/<id> for the full trace UI.';
COMMENT ON COLUMN public.messages.prompt_version_id IS
  'Exact prompts.id used to generate this outbound message. Lets us '
  'replay deterministically when debugging or A/B testing prompts.';

CREATE INDEX IF NOT EXISTS messages_langfuse_trace_idx
  ON public.messages (langfuse_trace_id)
  WHERE langfuse_trace_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS messages_prompt_version_idx
  ON public.messages (prompt_version_id, "timestamp" DESC)
  WHERE prompt_version_id IS NOT NULL;
